### ISSUE TITLE
Rename Findlib ppx-package

### ISSUE THREAD

**Issue by darioteixeira** [cryptosense/ocamllint#6]
There's an emerging convention that if project `foobar` ships with a single optional PPX syntax extension, then the Findlib name for it should be `foobar.ppx`. Referring to `ocamllint.ppx_lint` has a lot of redundancy.  Simply `ocamllint.ppx` would be better (unless you plan on adding other PPX to this project).

(Cool project, btw!)

**Comment by emillon** [comment]
Hi,

Glad you like it! This seems to be a good idea, I'll do this. Thanks!
